name: Valgrind Check

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  valgrind:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Install dependencies
      run: sudo apt-get update && sudo apt-get install -y valgrind
      
    - name: Build your C project
      run: make
      
    - name: Run program without ARGS
      run: valgrind --leak-check=full --error-exitcode=1 ./push_swap
    
    - name: Run program with ARG error
      run: valgrind --leak-check=full  ./push_swap "      " 1
    
    - name: Run program with ARG error duplicate
      run: valgrind --leak-check=full ./push_swap  1 1
    
    - name: Run program with ARG with sorted ARGS
      run: valgrind --leak-check=full --error-exitcode=1 ./push_swap  1 2 3 4 "5 6 7"
